### ISSUE TITLE
character mapping must return integer, None or unicode

### ISSUE THREAD

**Issue by edwinwow** [bodylabs/drf-to-s3#2]
character mapping must return integer, None or unicode,

any idea of this problem??

after i add:

secret_key_pre=self.get_aws_secret_key()
secret_key=secret_key_pre.encode()

i did get the upload_uri,

but it is not correct. 

return: signaturenotmatch.

thx

**Comment by paulmelnikow** [comment]
Hi! Sorry, but can't quite follow what you're asking. Can you show more of your code?

(Sorry for the late response too!)

**Comment by paulmelnikow** [comment]
Happy to debug this further if you can provide some more information.
